app:
  kafka:
    bootstrapServers: localhost:9092 #брокер, к которому подключаемся
    groupId: consumer-group-1   #айди группы потребителей
    enableAutoCommit: false  #нужно ли вручную подтверждать получение сообщения
    concurrency: 1 # колво потоков обработчиков
    maxPollRecords: 500 # макс колво извлекаемых сообщений за раз

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/messages
    username: user
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8090